-- MySQL Script generated by MySQL Workbench
-- mer. 28 oct. 2020 14:33:21 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema design_broderie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema design_broderie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `design_broderie` ;
USE `design_broderie` ;

-- -----------------------------------------------------
-- Table `design_broderie`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `design_broderie`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(50) NOT NULL,
  `reference` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `category_id` INT NOT NULL,
  FOREIGN KEY (category_id) REFERENCES category(id),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `design_broderie`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `design_broderie`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `design_broderie`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `design_broderie`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `company_name` VARCHAR(100) NULL,
  `address` VARCHAR(100) NOT NULL,
  `postcode` VARCHAR(20) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `quantity` INT NOT NULL,
  `size` VARCHAR(4) NOT NULL,
  `message` LONGTEXT NULL,
  `logo` BLOB NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `design_broderie`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_order_product_idx` ON `design_broderie`.`order` (`product_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


